// Mocks generated by Mockito 5.1.0 from annotations
// in app/test/biometrics_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:app/service/biometrics_service.dart' as _i3;
import 'package:app/utils/biometrics_result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeBiometricsResult_0 extends _i1.Fake implements _i2.BiometricsResult {
}

/// A class which mocks [BiometricsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricsService extends _i1.Mock implements _i3.BiometricsService {
  MockBiometricsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> checkAvailableBiometrics() =>
      (super.noSuchMethod(Invocation.method(#checkAvailableBiometrics, []),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<_i2.BiometricsResult> tryAuth(String? reason) =>
      (super.noSuchMethod(Invocation.method(#tryAuth, [reason]),
              returnValue:
                  Future<_i2.BiometricsResult>.value(_FakeBiometricsResult_0()))
          as _i4.Future<_i2.BiometricsResult>);
}
